### ISSUE TITLE
Create Documentation for POS Tagger 

### ISSUE THREAD

**Issue by djokester** [djokester/sangita#2]
The documentation for POS Tagger isn't present.
Have a look at **_[postagger.py](https://github.com/djokester/sangita/blob/master/sangita/hindi/postagger.py)_** insert the documentation for the same.

**Comment by cseas** [comment]
Can I work on this? Any guidelines?

**Comment by djokester** [comment]
@cesas I would suggest taking up the stemmer issue if you are not a beginner.
Also join this [Slack group](https://join.slack.com/t/sangitanlp/shared_invite/enQtMzc2NzMzODQ2ODU1LTRkOTUwODViMDBlNjIzZGNhZWIzNzc5MjM0Y2Y3YjYzMWY1NThjYmVkY2Y4M2RhODU5NzQ0MzZmODE4NmQ4ZmU) for communication
